baseURL = "https://takatoshiinaoka.github.io/slides/"
publishDir = "docs"
languageCode = "ja_JP"
title = "スライド用デモ・サイト"
theme = "reveal-hugo"

[outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true

[markup.goldmark.renderer]
  unsafe = true
[markup.highlight]
  codeFences = false




